### ISSUE TITLE
Follow Release Process for `3.0.0-alpha.3`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#380]
Releases: https://crates.io/crates/torrust-index-backend/versions

We should start publishing the crate with the new name: `torrust-index` (instead of `torrust-index-backend`).

From: [release_process.md](https://github.com/torrust/torrust-index/blob/develop/docs/release_process.md)

Comments in the Develop Branch:

- The `develop` branch has the `3.0.0-alpha.3-develop`.
- The version is bumped according to releases, new features, and breaking changes.

Process:

- [ ] The `develop` branch is ready for a release.
- [ ] [Stage](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#2-stage-develop-head-for-merging-into-the-main-branch) `develop` HEAD for merging into the `main` branch.
- [ ] [Create Release Commit](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#3-create-release-commit): `release: version 3.0.0-alpha.3`, that removes the `-develop` suffix.
- [ ] Create "Release Version `3.0.0-alpha.3`" pull request from from `staging/main` into `main` branch.
- [ ] Merge "Release Version `3.0.0-alpha.3`" pull request.
- [ ] [Push New Version](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#5-push-new-version-from-main-head-to-releasesvsemantic-version-branch) from `main` HEAD to `releases/v3.0.0-alpha.3` branch.
- [ ] **Check that the deployment is successful!**
- [ ] [Create Release Tag](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#5-push-new-version-from-main-head-to-releasesvsemantic-version-branch) `v3.0.0-alpha.3`.
- [ ] Create Release on Github from Tag.
- [ ] [Stage](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#8-stage-main-head-for-merging-into-the-develop-branch) `main` HEAD for merging into the `develop` branch.
- [ ] [Create Comment](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#9-create-comment-that-bumps-next-development-version) that bumps next development version.
- [ ] Create "Version `3.0.0-alpha.3` was Released" pull request from from `staging/develop` into `develop` branch.
- [ ] Merge "Version `3.0.0-alpha.3` was Released" pull request.

**Comment by josecelano** [comment]
We still have to publish the previous one: https://github.com/torrust/torrust-index/issues/349#issuecomment-1808471545

**Comment by josecelano** [comment]
I don't think we need this. I've released version 3.0.0-alpha.12 for all packages.
