### ISSUE TITLE
Overhaul E2E Tests

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#384]
From: https://github.com/torrust/torrust-index/pull/383#issuecomment-1810803438

E2E tests were reestablished [here](https://github.com/torrust/torrust-index/pull/383) after being disabled in this [PR](https://github.com/torrust/torrust-index/pull/338).

Only the essential execution was reestablished, but some other things are pending to fix/improve. This issue tracks the list of subtasks.

### Subtasks

- [x] https://github.com/torrust/torrust-index/issues/361
- [x] https://github.com/torrust/torrust-index/issues/386
- [x] https://github.com/torrust/torrust-index/issues/389
- [x] https://github.com/torrust/torrust-index/issues/254
- [x] https://github.com/torrust/torrust-index/issues/392
- [x] https://github.com/torrust/torrust-index/issues/390
- [x] https://github.com/torrust/torrust-index/issues/203
- [x] Review `e2e-env-reset.sh` scripts. The idea was to be able to run the E2E env and E2E test locally. Depends on #392. Deprecated. Reset scripts were removed, It can be done manually if needed. You only need to delete and recreate the database.
