### ISSUE TITLE
User ID extractor for handlers that require an user id

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-index#445]
Parent issue: #39.

### Tasks:
**New extractor**
- [x] User Id extractor (for handlers that require an user id)

**Status code and error**

- [x] Custom required logged-in user error

**Refactor handlers**
- [x] torrent upload torrent
- [x] torrent update torrent info
- [x] torrent delete torrent
- [x]  category add handler
- [x] category delete handler
- [x] settings get all handler
- [x] tag add handler
- [x] tag delete handler
- [x] user ban user handler
~~- [ ] proxy get proxy handler~~
