### ISSUE TITLE
Optional user ID extractor for handlers that require an optional user id

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-index#446]
Parent issue: #39.

### Tasks:
**New extractor**
- [ ] Optional user extractor (for handlers that take an optional user as a parameter)

**Refactor handlers**
- [ ] torrent download torrent handler
- [ ] torrent get torrent info handler
