### ISSUE TITLE
Configuration overhaul

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#586]
Relates to: https://github.com/torrust/torrust-tracker/issues/401

We should apply the same [improvements we applied to the Torrsut Tracker](https://github.com/torrust/torrust-tracker/issues/401).

### Subtasks (v3.0.0)

- [x] https://github.com/torrust/torrust-index/issues/587
- [x] https://github.com/torrust/torrust-index/issues/589
- [x] https://github.com/torrust/torrust-index/issues/581
- [x] https://github.com/torrust/torrust-index/issues/596
- [x] https://github.com/torrust/torrust-index/issues/599
- [x] https://github.com/torrust/torrust-index/issues/603
- [x] https://github.com/torrust/torrust-index/issues/605
- [x] https://github.com/torrust/torrust-index/issues/591

**Comment by josecelano** [comment]
All subtasks finished.
