### ISSUE TITLE
Configuration overhaul: version 2 for the configuration toml file (breaking changes)

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#591]
Parent issue: https://github.com/torrust/torrust-index/issues/586
Relates to: https://github.com/torrust/torrust-tracker/issues/878
Updated on: 2024-06-02 (added more changes)

There are two groups of changes. Changes in the 2024-05 group have already been implemented and merged.

### Changes (2024-07)

After a discussion, we decided to make more changes:

- [x] https://github.com/torrust/torrust-index/issues/674
- [x] https://github.com/torrust/torrust-index/issues/672
- [x] https://github.com/torrust/torrust-index/issues/673

### Changes (2024-06)

After a discussion, we decided to make more changes:

- [x] https://github.com/torrust/torrust-index/issues/651
- [x] https://github.com/torrust/torrust-index/issues/657
- [x] https://github.com/torrust/torrust-index/issues/652
- [x] https://github.com/torrust/torrust-index/issues/655
- [x] https://github.com/torrust/torrust-index/issues/654

Some are pending confirmation/feedback:

- [x] https://github.com/torrust/torrust-index/issues/653

#### Old toml version (before 2024-06 changes)

```toml
[logging]
log_level = "info"

[tracker]
mode = "public"

[auth]
email_on_signup = "optional"
secret_key = "MaxVerstappenWC2021"

[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"
```

**NOTE**: omitted non-changed fields.

#### New toml version (after 2024-06 changes)

```toml
version = "2"

[logging]
threshold = "info"

[tracker]
private = false
listed = false

[auth]
password_database_pepper = "MaxVerstappenWC2021"

[registration]
# Other future options related to registration in addition to mail.
# All options related to mail go into the mail subtype.

  [registration.mail]
  required = true
  verification_required = true

[mail]
from = "example@email.com"
reply_to = "noreply@email.com"
```

**NOTE**: omitted non-changed fields.

### Changes (2024-05)

1. Use TrackerMode from [torrust-tracker-primitives](https://github.com/torrust/torrust-tracker/blob/develop/packages/primitives/src/lib.rs#L66-L87) crate.

Enum variants (Index -> Tracker):

- `Public`             -> `Public`
- `Private`            -> `Private`
- `Whitelisted`        -> `Listed` 
- `PrivateWhitelisted` -> `PrivateListed`

Enum serialized values (Index -> Tracker):

- `Public`             -> `public`
- `Private`            -> `private`
- `Whitelisted`        -> `listed` 
- `PrivateWhitelisted` -> `private_listed`

We have to use the **Tracker** version (enum variant -> serialized value):

- `Public`        -> `public`
- `Private`       -> `private`
- `Listed`        -> `listed`
- `PrivateListed` -> `private_listed`

2. Include `log_level` in a new section `[loggging]`.

#### Old toml version (before 2024-05 changes)

```toml
log_level = "info"

[website]
name = "Torrust"

[tracker]
api_url = "http://localhost:1212"
mode = "Public"
token = "MyAccessToken"
token_valid_seconds = 7257600
url = "udp://localhost:6969"

[net]
port = 3001

# Uncomment if you want to enable TSL for development
#[net.tsl]
#ssl_cert_path = "./storage/index/lib/tls/localhost.crt"
#ssl_key_path = "./storage/index/lib/tls/localhost.key"

[auth]
email_on_signup = "Optional"
max_password_length = 64
min_password_length = 6
secret_key = "MaxVerstappenWC2021"

[database]
connect_url = "sqlite://data.db?mode=rwc"

[mail]
email_verification_enabled = false
from = "example@email.com"
password = ""
port = 25
reply_to = "noreply@email.com"
server = ""
username = ""

[image_cache]
capacity = 128000000
entry_size_limit = 4000000
max_request_timeout_ms = 1000
user_quota_bytes = 64000000
user_quota_period_seconds = 3600

[api]
default_torrent_page_size = 10
max_torrent_page_size = 30

[tracker_statistics_importer]
port = 3002
torrent_info_update_interval = 3600
```

#### New toml version (alfter 2024-05 changes)

```toml
[logging]
log_level = "info"

[website]
name = "Torrust"

[tracker]
api_url = "http://localhost:1212"
mode = "public"
token = "MyAccessToken"
token_valid_seconds = 7257600
url = "udp://localhost:6969"

[net]
base_url = "http://localhost"
bind_address = "0.0.0.0:3001"

# Uncomment if you want to enable TSL for development
#[net.tsl]
#ssl_cert_path = "./storage/index/lib/tls/localhost.crt"
#ssl_key_path = "./storage/index/lib/tls/localhost.key"

[auth]
email_on_signup = "Optional"
secret_key = "MaxVerstappenWC2021"

[auth.password_constraints]
max_password_length = 64
min_password_length = 6

[database]
connect_url = "sqlite://data.db?mode=rwc"

[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"

[mail.smtp]
port = 25
server = ""

[mail.smtp.credentials]
password = ""
username = ""

[image_cache]
capacity = 128000000
entry_size_limit = 4000000
max_request_timeout_ms = 1000
user_quota_bytes = 64000000
user_quota_period_seconds = 3600

[api]
default_torrent_page_size = 10
max_torrent_page_size = 30

[tracker_statistics_importer]
port = 3002
torrent_info_update_interval = 3600

```

**Notice**: 

- The new value `mode = "public"` instead of `mode = "Public"`.
- The `[net]` `bind_address`

cc @da2ce7

**Comment by josecelano** [comment]
Should we serialize all enums in lowercase? @da2ce7 . For example: `email_on_signup`.

**Comment by josecelano** [comment]
The `conenct_url` field in `[database]` section is actually defined in the [sqlx](https://github.com/launchbadge/sqlx/blob/main/sqlx-core/src/connection.rs#L10) crate

- Sqlite: `sqlite://data.db?mode=rwc`.
- Mysql: `mysql://root:root_secret_password@mysql:3306/torrust_index_e2e_testing`.
- PostgreSQL: `postgres://postgres:password@localhost/database`

It's a URL. We should decide if we want to stick to that representation. I think URL is a generic and standard enough format. So it's not a problem to be coupled to that format.

**Comment by josecelano** [comment]
Another question @da2ce7 is: should the default configuration be the development configuration?

```rust
pub const DEFAULT_PATH_CONFIG: &str = "./share/default/config/index.development.sqlite3.toml";
```

`./share/default/config/index.development.sqlite3.toml`:

```toml
log_level = "info"
```

Default values:

```toml
[website]
name = "Torrust"

[tracker]
url = "udp://localhost:6969"
mode = "Public"
api_url = "http://localhost:1212/"
token = "MyAccessToken"
token_valid_seconds = 7257600

[net]
port = 3001

[auth]
email_on_signup = "Optional"
min_password_length = 6
max_password_length = 64
secret_key = "MaxVerstappenWC2021"

[database]
connect_url = "sqlite://data.db?mode=rwc"

[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"
username = ""
password = ""
server = ""
port = 25

[image_cache]
max_request_timeout_ms = 1000
capacity = 128000000
entry_size_limit = 4000000
user_quota_period_seconds = 3600
user_quota_bytes = 64000000

[api]
default_torrent_page_size = 10
max_torrent_page_size = 30

[tracker_statistics_importer]
torrent_info_update_interval = 3600
port = 3002
```

I think it makes more sense if the default configuration is the production default configuration. That leads to another question: What should be the default production configuration? I think It could be the same. Maybe we just need to remove the `./share/default/config/index.development.sqlite3.toml` file and just use the default config when the user doesn't provide a config file path.

**Comment by josecelano** [comment]
I've also starting using this struct:

```rust
struct PasswordConstraints {
    pub min_password_length: usize,
    pub max_password_length: usize,
}
```

For the `auth` section in the toml file:

```toml
[auth]
email_on_signup = "Optional"
min_password_length = 6
max_password_length = 64
secret_key = "MaxVerstappenWC2021"
```

So maybe we could change it to:

```toml
[auth]
email_on_signup = "Optional"
secret_key = "MaxVerstappenWC2021"

[auth.password_constraints]
min_password_length = 6
max_password_length = 64
```

**Comment by josecelano** [comment]
Maybe we canb also refactor the `[mail]` section, from

```toml
[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"
username = ""
password = ""
server = ""
port = 25
```

to:

```toml
[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"

[mail.smtp]
server = ""
port = 25

[mail.smtp.credentials]
username = ""
password = ""
```

In JSON:

```json
{
  "mail": {
    "email_verification_enabled": false,
    "from": "example@email.com",
    "reply_to": "noreply@email.com",
    "smtp": {
      "server": "",
      "port": 25,
      "credentials": {
        "username": "",
        "password": ""
      }
    }
  }
}
```

**Comment by josecelano** [comment]
These breaking changes affect other repos:

- [ ] https://github.com/torrust/torrust-index-gui/issues/574
- [ ] https://github.com/torrust/torrust-compose/issues/18
- [ ] https://github.com/torrust/torrust-demo/issues/6
- [ ] https://github.com/torrust/torrust-website/issues/206

**Comment by josecelano** [comment]
I'm reopening just to track changes in affected repos ☝🏼.

**Comment by josecelano** [comment]
It seems these changes do not affect tutorials on the website. However, I've opened an [issue](https://github.com/torrust/torrust-website/issues/206) to check tutorials for setting up a local demo and the dev env.

**Comment by josecelano** [comment]
Today, we had a meeting, and we decided to include some more changes.

[Some of them have already been described in the tracker](https://github.com/torrust/torrust-tracker/issues/401#issuecomment-2180566059). See [here](https://github.com/torrust/torrust-tracker/issues/401#issuecomment-2180566059).

I'm going to to describe here only the extra changes which are specific for this repo.

### Improve naming and reorganize fields

Some changes we have discussed to improve the naming and fields have been reorganized:

The current values affected:

```
[auth]
email_on_signup = "Optional"
secret_key = "MaxVerstappenWC2021"

[mail]
email_verification_enabled = false
```

The new proposal:

```toml
[auth]
# Deprecated.
#secret_key = "MaxVerstappenWC2021"
# Rename secret_key to this. It's only used for this purpose for the time being.
password_database_pepper = "MaxVerstappenWC2021"

[registration]
# Whether we should include the email field in the registration form or not
email_on_profile = "optional" 
# Whether we require email verification or not. This requires [mail] service to be enabled. The app should panic when it starts if it's enabled but there is no mail server config provided.
verification_email = true 

# Optional mail configuration
[mail]
from = "example@email.com"
reply_to = "noreply@email.com"

# ...
```

Hey @da2ce7 I think you proposed the name `welcome_email` but I think you misunderstood the config value. THe `email_on_signup` does not mean the app sends a welcome email after the registration. It's used to collect the email for the user's profile.

- Required: the user must provide a valid email even if email verification is disabled.
- Optional: the app shows the email field in the registration form, but the user can omit it. It can be empty. Some user's profiles may have it and others may not.
- Ignored: the frontend app does not show the email field at all. However, the API accepts that param in the POST request but, it ignores it.

**Comment by josecelano** [comment]
The tracker mode was removed from the tracker. See https://github.com/torrust/torrust-index/issues/648.

We could keep the `TrackerMode`enum in this repo as an internal Index enum representing all tracker modes that affect the Index. Alternatively, we could remove it and use the new two flags: `private` and `listed. '

I would also change it here to follow changes in the tracker.

cc @da2ce7

**Comment by josecelano** [comment]
### New subtasks

- [ ] Config overhaul: add version to the configuration
- [ ] Config overhaul: rename `log_level` to `threshold`
- [ ] Config overhaul: rename `auth::secret_key` to `auth::password_database_pepper`
- [ ] Config overhaul: make mail-related configuration clearer
- [ ] Config overhaul: split `TrackerMode`into two flags `private` and `listed`

- Make some fields mandatory? @da2ce7
